language: python
python:
  - "3.4"
  - "2.7"
install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
script:
  - python setup.py install
  - nosetests --with-coverage --cover-package=clld_glottologfamily_plugin --with-doctest
before_install:
  pip install codecov
after_success:
  codecov
