language: python
python:
  - 3.5
  - 3.6
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
install:
  - pip install -e .[test]
script:
  - pytest --cov clld_glottologfamily_plugin --cov-report=term-missing
before_install:
  pip install codecov
after_success:
  - tox -e coverage-report
  - codecov
